version: '2'
services:
  rabbitmq:
    image: bitnami/rabbitmq:latest
    ports:
       - "5672:5672"
       - "15672:15672"
    environment:
      - RABBITMQ_PASSWORD=root
      - RABBITMQ_USERNAME=root