mail_support:
  host: exrates.top
  port: 25
  protocol: smtp
  user: mail@exrates.top
  password: R37yt7gEft

mail_mandrill:
  host: smtp.mandrillapp.com
  port: 587
  protocol: smtp
  user: Service
  password: dKD_WZ61VHQbQwWlRQI8cA

mail_info:
  host: exrates.top
  port: 25
  protocol: smtp
  user: no-reply@exrates.top
  password: E3ZW3397dV

default_mail_type: mandrill

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root

mail_info.allowedOnly: false
mail_info.allowedEmails: golvazin@gmail.com,avto12@i.ua,wayfarer2006@ukr.net,yagi7337@gmail.com,yagi3773@gmail.com,vlad.dziubak@gmail.com,nikita.dmytrenko@upholding.biz,oleg.podolyan@upholdingz.biz,oleg.kostiukevych@upholding.biz,listing@exrates.me

support.email: mail@exrates.top
mandrill.email: exrates.me
info.email: exrates.me

listing.email: listing@exrates.me
listing.subject: Listing request
server:
  port: 8081