mail_ses:
  host: email-smtp.us-east-1.amazonaws.com
  port: 587
  protocol: smtp
  user: AKIA6M5IMESXGM7DI2XJ
  password: BPg7g+834jBANU1aT57lZI3oowDQ8J5J4VWOOe6sxSq/

mail_sendgrid:
  host: smtp.sendgrid.net
  port: 25
  protocol: smtp
  user: StasGorobzeev
  password: gkYY1k23YJRUxN4R

spring:
  rabbitmq:
    host: rabbitmq-dev.service
    port: 5672
    username: developer
    password: eehei4AeJein

main.email: no-reply@exrates.me
main.email.name: Exrates-stage

server:
  port: 8081